// Kuratierte Rezepte zum direkt Nachkochen (Nährwerte pro Portion, aus den Zutatenmengen berechnet).
import type { DietMacro, DietRestriction } from './dietStyle'
import type { Meal } from '../types'

export interface CatalogRecipe {
  id: string
  title: string
  meal: Meal[]
  minutes: number
  servings: number
  /** Zutaten mit Mengen für das ganze Rezept */
  ingredients: string[]
  steps: string[]
  kcal: number
  protein: number
  carbs: number
  fat: number
  fiber: number
  sugar: number
  sat_fat: number
  salt: number
  /** Ernährungsweisen, zu denen das Rezept passt */
  restrictions: DietRestriction[]
  macros: DietMacro[]
}

export const RECIPE_CATALOG: CatalogRecipe[] = [
  {
    id: 'c-protein-overnight-oats-beeren',
    title: 'Protein-Overnight-Oats mit Beeren',
    meal: ['breakfast'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '60 g Haferflocken',
      '150 g Magerquark',
      '100 ml Milch (1,5 %)',
      '100 g Beerenmischung (TK)',
      '10 g Chiasamen',
      '1 Prise Zimt',
    ],
    steps: [
      'Haferflocken, Quark, Milch, Chiasamen und Zimt in einem Glas verrühren.',
      'Beeren darübergeben und abgedeckt über Nacht in den Kühlschrank stellen.',
      'Morgens umrühren und kalt genießen.',
    ],
    kcal: 455, protein: 32, carbs: 53, fat: 10,
    fiber: 14, sugar: 17, sat_fat: 2, salt: 0.3,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-skyr-bowl-himbeeren-mandeln',
    title: 'Skyr-Bowl mit Himbeeren und Mandeln',
    meal: ['breakfast', 'snack'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '250 g Skyr natur',
      '100 g Himbeeren',
      '30 g Haferflocken',
      '20 g Mandeln',
      '10 g Honig',
    ],
    steps: [
      'Skyr in eine Schüssel geben und glatt rühren.',
      'Mandeln grob hacken.',
      'Himbeeren, Haferflocken und Mandeln darauf verteilen.',
      'Mit Honig beträufeln.',
    ],
    kcal: 459, protein: 37, carbs: 42, fat: 13,
    fiber: 12, sugar: 23, sat_fat: 1, salt: 0.3,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-ruehrei-spinat-feta',
    title: 'Rührei mit Spinat und Feta',
    meal: ['breakfast', 'dinner'],
    minutes: 10,
    servings: 1,
    ingredients: [
      '3 Eier (Größe M)',
      '60 g Babyspinat',
      '30 g Feta',
      '1 TL Olivenöl',
      'Salz, Pfeffer',
    ],
    steps: [
      'Olivenöl in einer Pfanne erhitzen und den Spinat darin zusammenfallen lassen.',
      'Eier verquirlen, salzen, pfeffern und in die Pfanne geben.',
      'Bei mittlerer Hitze unter Rühren stocken lassen.',
      'Feta darüberbröseln und sofort servieren.',
    ],
    kcal: 392, protein: 29, carbs: 2, fat: 29,
    fiber: 2, sugar: 2, sat_fat: 11, salt: 2.0,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['high_protein', 'low_carb', 'keto', 'mediterranean'],
  },
  {
    id: 'c-avocado-ei-vollkornbrot',
    title: 'Avocado-Ei-Brot mit Tomaten',
    meal: ['breakfast'],
    minutes: 10,
    servings: 1,
    ingredients: [
      '2 Scheiben Vollkornbrot (100 g)',
      '½ Avocado (70 g)',
      '2 Eier (Größe M)',
      '60 g Kirschtomaten',
      '1 Spritzer Zitronensaft',
      'Salz, Pfeffer',
    ],
    steps: [
      'Eier 7 Minuten wachsweich kochen, abschrecken und pellen.',
      'Avocado mit Zitronensaft, Salz und Pfeffer zerdrücken.',
      'Brot damit bestreichen.',
      'Eier in Scheiben und Tomaten halbiert darauflegen.',
    ],
    kcal: 510, protein: 24, carbs: 42, fat: 24,
    fiber: 13, sugar: 6, sat_fat: 6, salt: 1.8,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: [],
  },
  {
    id: 'c-tofu-ruehrei-paprika',
    title: 'Tofu-Rührei mit Paprika und Spinat',
    meal: ['breakfast', 'dinner'],
    minutes: 10,
    servings: 1,
    ingredients: [
      '200 g Tofu natur',
      '½ rote Paprika (80 g)',
      '50 g Babyspinat',
      '½ kleine Zwiebel (30 g)',
      '2 TL Rapsöl',
      '½ TL Kurkuma',
      'Salz, Pfeffer',
    ],
    steps: [
      'Zwiebel und Paprika fein würfeln und im Öl 3 Minuten anbraten.',
      'Tofu mit den Händen hineinbröseln, mit Kurkuma, Salz und Pfeffer würzen.',
      'Unter Rühren 4 Minuten braten.',
      'Spinat unterheben, bis er zusammenfällt.',
    ],
    kcal: 423, protein: 32, carbs: 9, fat: 27,
    fiber: 4, sugar: 7, sat_fat: 3, salt: 0.9,
    restrictions: ['vegan', 'vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['high_protein', 'low_carb', 'keto'],
  },
  {
    id: 'c-erdnuss-bananen-porridge',
    title: 'Erdnuss-Bananen-Porridge',
    meal: ['breakfast'],
    minutes: 10,
    servings: 1,
    ingredients: [
      '80 g Haferflocken',
      '250 ml Sojadrink natur',
      '1 Banane (120 g)',
      '25 g Erdnussmus (100 % Erdnüsse)',
      '100 ml Wasser, 1 Prise Zimt',
    ],
    steps: [
      'Haferflocken mit Sojadrink und Wasser aufkochen.',
      'Unter Rühren 3–4 Minuten sämig köcheln lassen.',
      'Die Hälfte der Banane hineinzerdrücken, Rest in Scheiben schneiden.',
      'Porridge mit Bananenscheiben, Erdnussmus und Zimt toppen.',
    ],
    kcal: 640, protein: 27, carbs: 75, fat: 23,
    fiber: 14, sugar: 22, sat_fat: 4, salt: 0.3,
    restrictions: ['vegan', 'vegetarian', 'pescetarian'],
    macros: ['balanced'],
  },
  {
    id: 'c-chia-kokos-pudding-himbeeren',
    title: 'Chia-Kokos-Pudding mit Himbeeren',
    meal: ['breakfast', 'snack'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '30 g Chiasamen',
      '120 ml Kokosmilch',
      '60 g Himbeeren',
      '80 ml Wasser',
    ],
    steps: [
      'Kokosmilch mit Wasser verrühren.',
      'Chiasamen einrühren, nach 5 Minuten nochmals umrühren.',
      'Mindestens 2 Stunden oder über Nacht kühlen.',
      'Mit Himbeeren servieren.',
    ],
    kcal: 368, protein: 8, carbs: 7, fat: 31,
    fiber: 14, sugar: 5, sat_fat: 20, salt: 0.1,
    restrictions: ['vegan', 'vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['low_carb', 'keto'],
  },
  {
    id: 'c-huettenkaese-brot-gurke-radieschen',
    title: 'Hüttenkäse-Brot mit Gurke und Radieschen',
    meal: ['breakfast', 'dinner'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '2 Scheiben Vollkornbrot (100 g)',
      '200 g Hüttenkäse',
      '100 g Gurke',
      '5 Radieschen (50 g)',
      'Schnittlauch, Pfeffer',
    ],
    steps: [
      'Gurke und Radieschen in dünne Scheiben schneiden.',
      'Brot großzügig mit Hüttenkäse bestreichen.',
      'Gemüse darauf verteilen.',
      'Mit Schnittlauch und Pfeffer bestreuen.',
    ],
    kcal: 423, protein: 32, carbs: 46, fat: 10,
    fiber: 9, sugar: 10, sat_fat: 6, salt: 2.6,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-raeucherlachs-brot-frischkaese',
    title: 'Räucherlachs-Brot mit Frischkäse und Dill',
    meal: ['breakfast'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '2 Scheiben Vollkornbrot (100 g)',
      '40 g Frischkäse (leicht)',
      '75 g Räucherlachs',
      '60 g Gurke',
      '1 Spritzer Zitronensaft',
      'Dill, Pfeffer',
    ],
    steps: [
      'Brot mit Frischkäse bestreichen.',
      'Gurke in feine Scheiben schneiden und auflegen.',
      'Räucherlachs darauf verteilen.',
      'Mit Zitronensaft, Dill und Pfeffer abschmecken.',
    ],
    kcal: 389, protein: 27, carbs: 41, fat: 12,
    fiber: 8, sugar: 5, sat_fat: 3, salt: 3.7,
    restrictions: ['pescetarian'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-bananen-quark-pancakes',
    title: 'Bananen-Quark-Pancakes',
    meal: ['breakfast'],
    minutes: 20,
    servings: 1,
    ingredients: [
      '60 g Haferflocken (fein)',
      '1 kleine Banane (100 g)',
      '2 Eier (Größe M)',
      '150 g Magerquark',
      '1 TL Rapsöl',
      '80 g Heidelbeeren',
      '½ TL Backpulver, 1 Prise Zimt',
    ],
    steps: [
      'Banane zerdrücken und mit Eiern, Quark, Haferflocken, Backpulver und Zimt verrühren.',
      '5 Minuten quellen lassen.',
      'Öl in einer Pfanne erhitzen und kleine Pancakes je Seite 2 Minuten backen.',
      'Mit Heidelbeeren servieren.',
    ],
    kcal: 664, protein: 43, carbs: 68, fat: 22,
    fiber: 12, sugar: 30, sat_fat: 5, salt: 0.6,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-vegane-protein-joghurt-bowl',
    title: 'Vegane Protein-Joghurt-Bowl',
    meal: ['breakfast', 'snack'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '250 g Sojajoghurt natur',
      '20 g veganes Proteinpulver (Vanille)',
      '40 g Haferflocken',
      '100 g Beerenmischung (TK, aufgetaut)',
      '15 g Walnüsse',
    ],
    steps: [
      'Sojajoghurt mit dem Proteinpulver glatt rühren.',
      'In eine Schüssel geben.',
      'Haferflocken, Beeren und gehackte Walnüsse darauf verteilen.',
    ],
    kcal: 494, protein: 35, carbs: 37, fat: 20,
    fiber: 12, sugar: 9, sat_fat: 3, salt: 0.6,
    restrictions: ['vegan', 'vegetarian', 'pescetarian'],
    macros: ['high_protein'],
  },
  {
    id: 'c-shakshuka-feta',
    title: 'Shakshuka mit Feta',
    meal: ['breakfast', 'lunch', 'dinner'],
    minutes: 25,
    servings: 2,
    ingredients: [
      '1 Dose gehackte Tomaten (400 g)',
      '4 Eier (Größe M)',
      '1 rote Paprika (150 g)',
      '1 Zwiebel (80 g)',
      '2 Knoblauchzehen',
      '2 TL Olivenöl',
      '40 g Feta',
      'Kreuzkümmel, Paprikapulver, Salz, Pfeffer',
    ],
    steps: [
      'Zwiebel, Knoblauch und Paprika würfeln und im Olivenöl 5 Minuten anbraten.',
      'Tomaten und Gewürze zugeben und 8 Minuten einköcheln lassen.',
      'Vier Mulden formen, Eier hineinschlagen und abgedeckt 6–8 Minuten stocken lassen.',
      'Mit zerbröseltem Feta servieren.',
    ],
    kcal: 355, protein: 22, carbs: 15, fat: 22,
    fiber: 4, sugar: 14, sat_fat: 7, salt: 1.8,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['low_carb', 'mediterranean'],
  },
  {
    id: 'c-lachs-ofengemuese-feta',
    title: 'Lachs-Ofengemüse mit Feta',
    meal: ['lunch', 'dinner'],
    minutes: 30,
    servings: 2,
    ingredients: [
      '2 Lachsfilets (à 125 g)',
      '1 Zucchini (300 g)',
      '1 große rote Paprika (200 g)',
      '200 g Kirschtomaten',
      '1 rote Zwiebel (80 g)',
      '60 g Feta',
      '1 EL Olivenöl',
      'Oregano, Salz, Pfeffer',
    ],
    steps: [
      'Ofen auf 200 °C (Umluft 180 °C) vorheizen.',
      'Gemüse grob schneiden, mit Öl, Oregano, Salz und Pfeffer auf einem Blech mischen und 10 Minuten backen.',
      'Lachs auf das Gemüse legen, Feta darüberbröseln.',
      'Weitere 12–15 Minuten garen.',
    ],
    kcal: 495, protein: 35, carbs: 14, fat: 32,
    fiber: 6, sugar: 13, sat_fat: 9, salt: 1.7,
    restrictions: ['pescetarian', 'unprocessed'],
    macros: ['high_protein', 'low_carb', 'mediterranean'],
  },
  {
    id: 'c-zitronen-haehnchen-reis-brokkoli',
    title: 'Zitronen-Hähnchen mit Reis und Brokkoli',
    meal: ['lunch', 'dinner'],
    minutes: 25,
    servings: 2,
    ingredients: [
      '300 g Hähnchenbrustfilet',
      '140 g Basmatireis',
      '300 g Brokkoli',
      '2 TL Olivenöl',
      '2 Knoblauchzehen',
      'Saft von ½ Zitrone',
      'Salz, Pfeffer, Paprikapulver',
    ],
    steps: [
      'Reis nach Packungsanweisung garen, Brokkoli die letzten 5 Minuten mitdämpfen.',
      'Hähnchen in Streifen schneiden, würzen und im Öl 6–7 Minuten goldbraun braten.',
      'Gehackten Knoblauch und Zitronensaft zugeben und kurz schwenken.',
      'Mit Reis und Brokkoli anrichten.',
    ],
    kcal: 502, protein: 46, carbs: 60, fat: 8,
    fiber: 5, sugar: 3, sat_fat: 1, salt: 1.0,
    restrictions: ['unprocessed'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-rote-linsen-curry-spinat',
    title: 'Rote-Linsen-Curry mit Spinat',
    meal: ['lunch', 'dinner'],
    minutes: 25,
    servings: 2,
    ingredients: [
      '150 g rote Linsen',
      '150 ml Kokosmilch',
      '1 Dose gehackte Tomaten (400 g)',
      '1 Zwiebel (80 g)',
      '2 Knoblauchzehen',
      '100 g Babyspinat',
      '1 TL Rapsöl',
      '2 TL Currypulver, Salz',
      '300 ml Wasser',
    ],
    steps: [
      'Zwiebel und Knoblauch hacken und im Öl glasig dünsten, Currypulver kurz mitrösten.',
      'Linsen, Tomaten, Kokosmilch und Wasser zugeben.',
      '15 Minuten köcheln lassen, bis die Linsen weich sind.',
      'Spinat unterrühren und mit Salz abschmecken.',
    ],
    kcal: 472, protein: 23, carbs: 48, fat: 18,
    fiber: 12, sugar: 12, sat_fat: 12, salt: 1.1,
    restrictions: ['vegan', 'vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['balanced'],
  },
  {
    id: 'c-chili-sin-carne',
    title: 'Chili sin Carne mit Kidneybohnen',
    meal: ['lunch', 'dinner'],
    minutes: 25,
    servings: 2,
    ingredients: [
      '1 Dose Kidneybohnen (250 g abgetropft)',
      '80 g rote Linsen',
      '1 kleine Dose Mais (140 g abgetropft)',
      '1 Dose gehackte Tomaten (400 g)',
      '1 rote Paprika (150 g)',
      '1 Zwiebel (80 g)',
      '2 TL Olivenöl',
      'Chili, Kreuzkümmel, Paprikapulver, Salz',
      '250 ml Wasser',
    ],
    steps: [
      'Zwiebel und Paprika würfeln und im Öl 4 Minuten anbraten.',
      'Gewürze kurz mitrösten.',
      'Linsen, Tomaten und Wasser zugeben und 12 Minuten köcheln.',
      'Bohnen und Mais unterrühren, 5 Minuten heiß werden lassen und abschmecken.',
    ],
    kcal: 441, protein: 24, carbs: 60, fat: 8,
    fiber: 18, sugar: 17, sat_fat: 1, salt: 2.2,
    restrictions: ['vegan', 'vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['balanced'],
  },
  {
    id: 'c-chili-con-carne',
    title: 'Chili con Carne',
    meal: ['lunch', 'dinner'],
    minutes: 30,
    servings: 2,
    ingredients: [
      '300 g Rinderhack (mager, 5 % Fett)',
      '1 Dose Kidneybohnen (250 g abgetropft)',
      '1 kleine Dose Mais (140 g abgetropft)',
      '1 Dose gehackte Tomaten (400 g)',
      '1 rote Paprika (150 g)',
      '1 Zwiebel (80 g)',
      '2 TL Olivenöl',
      'Chili, Kreuzkümmel, Salz, Pfeffer',
    ],
    steps: [
      'Hack im Öl krümelig braten.',
      'Zwiebel und Paprika würfeln, zugeben und 3 Minuten mitbraten.',
      'Tomaten und Gewürze zugeben und 15 Minuten köcheln.',
      'Bohnen und Mais unterrühren, erhitzen und abschmecken.',
    ],
    kcal: 506, protein: 46, carbs: 41, fat: 15,
    fiber: 13, sugar: 17, sat_fat: 4, salt: 2.4,
    restrictions: ['unprocessed'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-vollkornpasta-thunfisch-tomate',
    title: 'Vollkornpasta mit Thunfisch-Tomatensauce',
    meal: ['lunch', 'dinner'],
    minutes: 20,
    servings: 2,
    ingredients: [
      '160 g Vollkornnudeln',
      '2 Dosen Thunfisch im eigenen Saft (260 g abgetropft)',
      '1 Dose gehackte Tomaten (400 g)',
      '1 Zwiebel (80 g)',
      '2 Knoblauchzehen',
      '1 EL Olivenöl',
      '20 g Parmesan',
      'Oregano, Salz, Pfeffer',
    ],
    steps: [
      'Nudeln nach Packungsanweisung kochen.',
      'Zwiebel und Knoblauch hacken und im Öl glasig dünsten.',
      'Tomaten und Oregano zugeben, 8 Minuten köcheln, dann Thunfisch unterheben.',
      'Mit den Nudeln mischen und mit Parmesan bestreuen.',
    ],
    kcal: 580, protein: 50, carbs: 58, fat: 14,
    fiber: 9, sugar: 11, sat_fat: 4, salt: 1.9,
    restrictions: ['pescetarian', 'unprocessed'],
    macros: ['balanced', 'high_protein', 'mediterranean'],
  },
  {
    id: 'c-garnelen-zucchini-knoblauch',
    title: 'Knoblauch-Garnelen mit Zucchini',
    meal: ['lunch', 'dinner'],
    minutes: 15,
    servings: 2,
    ingredients: [
      '400 g Garnelen (TK, aufgetaut)',
      '2 Zucchini (500 g)',
      '100 g Kirschtomaten',
      '3 Knoblauchzehen',
      '2 EL Olivenöl',
      '30 g Parmesan',
      'Chiliflocken, Salz, Pfeffer',
    ],
    steps: [
      'Zucchini in Halbmonde schneiden und in 1 EL Öl 5 Minuten braten.',
      'Restliches Öl, Knoblauch und Garnelen zugeben und 3–4 Minuten braten, bis sie rosa sind.',
      'Tomaten halbieren und kurz mitschwenken.',
      'Mit Chili, Salz und Pfeffer würzen und Parmesan darüberreiben.',
    ],
    kcal: 381, protein: 46, carbs: 9, fat: 17,
    fiber: 3, sugar: 6, sat_fat: 5, salt: 2.3,
    restrictions: ['pescetarian', 'unprocessed'],
    macros: ['high_protein', 'low_carb', 'keto', 'mediterranean'],
  },
  {
    id: 'c-puten-gemuese-curry-reis',
    title: 'Puten-Gemüse-Curry mit Basmatireis',
    meal: ['lunch', 'dinner'],
    minutes: 25,
    servings: 2,
    ingredients: [
      '300 g Putenbrust',
      '120 g Basmatireis',
      '150 ml Kokosmilch',
      '1 große Paprika (200 g)',
      '½ Zucchini (150 g)',
      '1 Zwiebel (80 g)',
      '2 TL Rapsöl',
      '2 TL Currypulver, Salz',
    ],
    steps: [
      'Reis nach Packungsanweisung kochen.',
      'Pute in Streifen schneiden und im Öl 4 Minuten anbraten.',
      'Zwiebel, Paprika und Zucchini würfeln, zugeben und Currypulver darüberstäuben.',
      'Kokosmilch angießen und 8 Minuten köcheln, mit Salz abschmecken und mit Reis servieren.',
    ],
    kcal: 607, protein: 44, carbs: 58, fat: 21,
    fiber: 4, sugar: 10, sat_fat: 13, salt: 1.0,
    restrictions: ['unprocessed'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-quinoa-bowl-kichererbsen-feta',
    title: 'Mediterrane Quinoa-Bowl mit Kichererbsen und Feta',
    meal: ['lunch', 'dinner'],
    minutes: 20,
    servings: 2,
    ingredients: [
      '120 g Quinoa',
      '1 Dose Kichererbsen (240 g abgetropft)',
      '½ Gurke (200 g)',
      '200 g Kirschtomaten',
      '80 g Feta',
      '30 g schwarze Oliven',
      '1 EL Olivenöl',
      'Saft von ½ Zitrone',
      'Petersilie, Salz, Pfeffer',
    ],
    steps: [
      'Quinoa gründlich waschen und in der doppelten Menge Wasser 12 Minuten garen.',
      'Gurke und Tomaten klein schneiden, Kichererbsen abspülen.',
      'Alles mit Olivenöl, Zitronensaft, Salz und Pfeffer mischen.',
      'Mit Feta, Oliven und Petersilie anrichten.',
    ],
    kcal: 589, protein: 25, carbs: 57, fat: 25,
    fiber: 15, sugar: 6, sat_fat: 8, salt: 2.4,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['balanced', 'mediterranean'],
  },
  {
    id: 'c-hueftsteak-kartoffeln-bohnen',
    title: 'Hüftsteak mit Rosmarinkartoffeln und Bohnen',
    meal: ['lunch', 'dinner'],
    minutes: 30,
    servings: 1,
    ingredients: [
      '1 Hüftsteak (200 g)',
      '350 g Kartoffeln',
      '200 g grüne Bohnen (TK)',
      '1 EL Olivenöl',
      '1 TL Butter',
      'Rosmarin, Salz, Pfeffer',
    ],
    steps: [
      'Kartoffeln vierteln, mit 2 TL Öl, Rosmarin und Salz mischen und bei 220 °C 25 Minuten rösten.',
      'Bohnen 8 Minuten in Salzwasser garen und in Butter schwenken.',
      'Steak trocken tupfen, im restlichen Öl je Seite 2–3 Minuten scharf braten.',
      '3 Minuten ruhen lassen, salzen, pfeffern und mit Kartoffeln und Bohnen servieren.',
    ],
    kcal: 723, protein: 55, carbs: 60, fat: 27,
    fiber: 12, sugar: 7, sat_fat: 8, salt: 1.8,
    restrictions: ['unprocessed'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-suesskartoffel-kichererbsen-bowl-tahini',
    title: 'Süßkartoffel-Kichererbsen-Bowl mit Tahini',
    meal: ['lunch', 'dinner'],
    minutes: 30,
    servings: 1,
    ingredients: [
      '1 Süßkartoffel (300 g)',
      '200 g Kichererbsen (Dose, abgetropft)',
      '50 g Babyspinat',
      '25 g Tahini',
      '2 TL Olivenöl',
      'Saft von ½ Zitrone',
      'Paprikapulver, Kreuzkümmel, Salz',
    ],
    steps: [
      'Ofen auf 220 °C vorheizen, Süßkartoffel würfeln.',
      'Süßkartoffel und Kichererbsen mit Öl und Gewürzen mischen und 25 Minuten rösten.',
      'Tahini mit Zitronensaft, 2 EL Wasser und Salz glatt rühren.',
      'Spinat in eine Schale geben, Ofengemüse darauf, mit Tahini-Sauce beträufeln.',
    ],
    kcal: 742, protein: 24, carbs: 82, fat: 29,
    fiber: 27, sugar: 14, sat_fat: 4, salt: 2.4,
    restrictions: ['vegan', 'vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['balanced'],
  },
  {
    id: 'c-seelachs-kartoffeln-spinat',
    title: 'Seelachs mit Kartoffeln und Rahmspinat-Light',
    meal: ['lunch', 'dinner'],
    minutes: 25,
    servings: 2,
    ingredients: [
      '2 Seelachsfilets (à 150 g, TK aufgetaut)',
      '500 g Kartoffeln',
      '300 g Blattspinat (TK)',
      '50 ml Milch (1,5 %)',
      '10 g Butter',
      '2 TL Olivenöl',
      '1 Spritzer Zitronensaft',
      'Muskat, Salz, Pfeffer',
    ],
    steps: [
      'Kartoffeln 20 Minuten in Salzwasser garen.',
      'Spinat mit Milch und Butter erhitzen, mit Muskat und Salz würzen.',
      'Fisch salzen und im Öl je Seite 3–4 Minuten braten.',
      'Mit Zitronensaft beträufeln und mit Beilagen anrichten.',
    ],
    kcal: 426, protein: 37, carbs: 40, fat: 11,
    fiber: 9, sugar: 4, sat_fat: 4, salt: 1.2,
    restrictions: ['pescetarian', 'unprocessed'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-tofu-gemuese-erdnusssauce',
    title: 'Tofu-Gemüse-Pfanne mit Erdnusssauce',
    meal: ['lunch', 'dinner'],
    minutes: 25,
    servings: 2,
    ingredients: [
      '400 g Tofu natur',
      '120 g Basmatireis',
      '250 g Brokkoli',
      '2 Karotten (150 g)',
      '1 rote Paprika (150 g)',
      '30 g Erdnussmus',
      '2 EL Sojasauce',
      '2 TL Rapsöl',
      '1 Stück Ingwer, Saft von ½ Limette',
    ],
    steps: [
      'Reis nach Packungsanweisung kochen.',
      'Tofu würfeln und im Öl rundum knusprig braten, herausnehmen.',
      'Gemüse klein schneiden und 5–6 Minuten in der Pfanne garen.',
      'Erdnussmus mit Sojasauce, geriebenem Ingwer, Limette und 4 EL Wasser verrühren.',
      'Tofu und Sauce zum Gemüse geben, durchschwenken und mit Reis servieren.',
    ],
    kcal: 730, protein: 45, carbs: 63, fat: 30,
    fiber: 11, sugar: 11, sat_fat: 4, salt: 2.0,
    restrictions: ['vegan', 'vegetarian', 'pescetarian'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-haehnchen-wrap-joghurt-dip',
    title: 'Hähnchen-Wrap mit Joghurt-Dip',
    meal: ['lunch'],
    minutes: 15,
    servings: 1,
    ingredients: [
      '2 Vollkorn-Tortillas (124 g)',
      '150 g Hähnchenbrustfilet',
      '100 g griechischer Joghurt (2 %)',
      '1 Handvoll Blattsalat',
      '1 Tomate (80 g)',
      '50 g Gurke',
      '1 TL Rapsöl',
      'Knoblauch, Paprikapulver, Salz',
    ],
    steps: [
      'Hähnchen in Streifen schneiden, würzen und im Öl 6 Minuten braten.',
      'Joghurt mit etwas Knoblauch, Salz und fein geriebener Gurke verrühren.',
      'Tortillas kurz in der Pfanne erwärmen.',
      'Mit Dip bestreichen, mit Salat, Tomate und Hähnchen belegen und einrollen.',
    ],
    kcal: 670, protein: 57, carbs: 66, fat: 18,
    fiber: 9, sugar: 11, sat_fat: 5, salt: 2.8,
    restrictions: [],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-vollkorn-spaghetti-bolognese',
    title: 'Vollkorn-Spaghetti Bolognese',
    meal: ['lunch', 'dinner'],
    minutes: 30,
    servings: 2,
    ingredients: [
      '200 g Vollkornspaghetti',
      '300 g Rinderhack (mager, 5 % Fett)',
      '500 g passierte Tomaten',
      '1 Zwiebel (80 g)',
      '1 Karotte (100 g)',
      '1 EL Olivenöl',
      '30 g Parmesan',
      'Oregano, Salz, Pfeffer',
    ],
    steps: [
      'Zwiebel und Karotte fein würfeln und im Öl 3 Minuten anbraten.',
      'Hack zugeben und krümelig braten.',
      'Passierte Tomaten und Oregano zugeben und 15 Minuten köcheln.',
      'Spaghetti parallel kochen, mit der Sauce mischen und mit Parmesan servieren.',
    ],
    kcal: 735, protein: 53, carbs: 73, fat: 23,
    fiber: 13, sugar: 16, sat_fat: 8, salt: 1.3,
    restrictions: ['unprocessed'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-griechischer-salat-haehnchen',
    title: 'Griechischer Bauernsalat mit Hähnchen',
    meal: ['lunch', 'dinner'],
    minutes: 15,
    servings: 1,
    ingredients: [
      '150 g Hähnchenbrustfilet',
      '150 g Gurke',
      '2 Tomaten (150 g)',
      '¼ grüne Paprika (50 g)',
      '¼ rote Zwiebel (30 g)',
      '40 g Feta',
      '20 g Kalamata-Oliven',
      '2 TL Olivenöl',
      'Oregano, Salz, Pfeffer',
    ],
    steps: [
      'Hähnchen würzen und in einer beschichteten Pfanne mit 1 TL Öl 6–7 Minuten braten.',
      'Gurke, Tomaten, Paprika und Zwiebel grob schneiden.',
      'Gemüse mit restlichem Öl, Oregano, Salz und Pfeffer mischen.',
      'Hähnchen in Scheiben, Feta und Oliven daraufgeben.',
    ],
    kcal: 452, protein: 45, carbs: 11, fat: 24,
    fiber: 5, sugar: 11, sat_fat: 8, salt: 2.4,
    restrictions: ['unprocessed'],
    macros: ['high_protein', 'low_carb', 'mediterranean'],
  },
  {
    id: 'c-lachs-poke-bowl',
    title: 'Lachs-Poke-Bowl mit Edamame und Avocado',
    meal: ['lunch', 'dinner'],
    minutes: 25,
    servings: 1,
    ingredients: [
      '1 Lachsfilet (150 g)',
      '80 g Basmatireis',
      '80 g Edamame (TK, geschält)',
      '½ Avocado (70 g)',
      '80 g Gurke',
      '½ Karotte (50 g)',
      '1 EL Sojasauce',
    ],
    steps: [
      'Reis nach Packungsanweisung kochen, Edamame die letzten 3 Minuten mitgaren.',
      'Lachs ohne Öl in der Pfanne auf der Hautseite 4 Minuten, dann 2 Minuten auf der anderen Seite braten.',
      'Gurke, Karotte und Avocado schneiden.',
      'Alles auf dem Reis anrichten und mit Sojasauce beträufeln.',
    ],
    kcal: 827, protein: 48, carbs: 72, fat: 36,
    fiber: 12, sugar: 6, sat_fat: 6, salt: 2.5,
    restrictions: ['pescetarian'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-thunfisch-avocado-salat',
    title: 'Thunfisch-Avocado-Salat',
    meal: ['dinner', 'lunch'],
    minutes: 10,
    servings: 1,
    ingredients: [
      '1 Dose Thunfisch im eigenen Saft (130 g abgetropft)',
      '½ Avocado (70 g)',
      '100 g Gurke',
      '60 g Blattsalat',
      '60 g Kirschtomaten',
      '2 TL Olivenöl',
      '1 EL Zitronensaft',
      'Salz, Pfeffer',
    ],
    steps: [
      'Salat waschen und in eine Schüssel geben.',
      'Gurke, Tomaten und Avocado klein schneiden und dazugeben.',
      'Thunfisch abtropfen lassen und darauf verteilen.',
      'Mit Öl, Zitronensaft, Salz und Pfeffer anmachen.',
    ],
    kcal: 389, protein: 37, carbs: 6, fat: 22,
    fiber: 7, sugar: 5, sat_fat: 3, salt: 1.5,
    restrictions: ['pescetarian', 'unprocessed'],
    macros: ['high_protein', 'low_carb', 'keto', 'mediterranean'],
  },
  {
    id: 'c-zucchini-nudeln-pesto-haehnchen',
    title: 'Zucchini-Nudeln mit Pesto und Hähnchen',
    meal: ['dinner'],
    minutes: 15,
    servings: 1,
    ingredients: [
      '150 g Hähnchenbrustfilet',
      '1 Zucchini (300 g)',
      '30 g grünes Pesto',
      '50 g Kirschtomaten',
      '10 g Parmesan',
      '1 TL Olivenöl',
      'Salz, Pfeffer',
    ],
    steps: [
      'Zucchini mit dem Spiralschneider oder Sparschäler in Streifen schneiden.',
      'Hähnchen in Streifen im Öl 6 Minuten braten, salzen und pfeffern.',
      'Zucchini-Nudeln zugeben und 2 Minuten mitschwenken.',
      'Pesto und halbierte Tomaten unterheben, mit Parmesan servieren.',
    ],
    kcal: 445, protein: 45, carbs: 9, fat: 24,
    fiber: 5, sugar: 8, sat_fat: 5, salt: 1.6,
    restrictions: [],
    macros: ['high_protein', 'low_carb', 'keto'],
  },
  {
    id: 'c-vollkorn-quesadilla-bohnen-mais',
    title: 'Vollkorn-Quesadilla mit Bohnen und Mais',
    meal: ['dinner', 'lunch'],
    minutes: 15,
    servings: 1,
    ingredients: [
      '2 Vollkorn-Tortillas (124 g)',
      '120 g schwarze Bohnen (Dose)',
      '50 g Mais (Dose)',
      '40 g geriebener Gouda',
      '60 g Paprika',
      '60 g griechischer Joghurt (2 %) zum Dippen',
      'Kreuzkümmel, Chili',
    ],
    steps: [
      'Bohnen abspülen und mit einer Gabel grob zerdrücken, mit Kreuzkümmel und Chili würzen.',
      'Paprika fein würfeln.',
      'Eine Tortilla mit Bohnen, Mais, Paprika und Käse belegen, zweite darauflegen.',
      'In einer Pfanne ohne Fett je Seite 2–3 Minuten knusprig braten und mit Joghurt servieren.',
    ],
    kcal: 741, protein: 37, carbs: 88, fat: 23,
    fiber: 18, sugar: 12, sat_fat: 12, salt: 3.1,
    restrictions: ['vegetarian', 'pescetarian'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-tomate-mozzarella-rucola',
    title: 'Tomate-Mozzarella mit Rucola',
    meal: ['dinner', 'snack'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '1 Kugel Mozzarella light (125 g)',
      '2–3 Tomaten (200 g)',
      '30 g Rucola',
      '2 TL Olivenöl',
      '1 TL Balsamico',
      'Basilikum, Salz, Pfeffer',
    ],
    steps: [
      'Tomaten und Mozzarella in Scheiben schneiden.',
      'Abwechselnd auf einem Teller auf dem Rucola anrichten.',
      'Mit Olivenöl und Balsamico beträufeln.',
      'Mit Basilikum, Salz und Pfeffer bestreuen.',
    ],
    kcal: 340, protein: 26, carbs: 8, fat: 22,
    fiber: 3, sugar: 8, sat_fat: 9, salt: 1.1,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['high_protein', 'low_carb', 'keto', 'mediterranean'],
  },
  {
    id: 'c-lachs-knoblauch-spinat',
    title: 'Lachsfilet auf Knoblauch-Spinat',
    meal: ['dinner'],
    minutes: 15,
    servings: 1,
    ingredients: [
      '1 Lachsfilet (150 g)',
      '200 g Babyspinat',
      '10 g Butter',
      '1 Knoblauchzehe',
      '1 EL Zitronensaft',
      'Salz, Pfeffer',
    ],
    steps: [
      'Lachs salzen und in 5 g Butter auf der Hautseite 4 Minuten, dann 2–3 Minuten auf der anderen Seite braten.',
      'Herausnehmen und warm halten.',
      'Restliche Butter und Knoblauch in die Pfanne geben, Spinat zusammenfallen lassen.',
      'Mit Salz, Pfeffer und Zitronensaft abschmecken und mit dem Lachs servieren.',
    ],
    kcal: 426, protein: 35, carbs: 3, fat: 29,
    fiber: 5, sugar: 1, sat_fat: 9, salt: 1.1,
    restrictions: ['pescetarian', 'unprocessed'],
    macros: ['high_protein', 'low_carb', 'keto', 'mediterranean'],
  },
  {
    id: 'c-puten-zucchini-pfanne-feta',
    title: 'Puten-Zucchini-Pfanne mit Feta',
    meal: ['dinner', 'lunch'],
    minutes: 15,
    servings: 1,
    ingredients: [
      '150 g Putenbrust',
      '1 Zucchini (300 g)',
      '1 Tomate (100 g)',
      '30 g Feta',
      '2 TL Olivenöl',
      'Thymian, Salz, Pfeffer',
    ],
    steps: [
      'Pute in Würfel schneiden und im Öl 5 Minuten anbraten.',
      'Zucchini und Tomate würfeln und zugeben.',
      'Mit Thymian, Salz und Pfeffer 5 Minuten weiterbraten.',
      'Feta darüberbröseln und servieren.',
    ],
    kcal: 402, protein: 47, carbs: 9, fat: 19,
    fiber: 5, sugar: 9, sat_fat: 6, salt: 1.8,
    restrictions: ['unprocessed'],
    macros: ['high_protein', 'low_carb', 'keto', 'mediterranean'],
  },
  {
    id: 'c-kichererbsen-avocado-salat',
    title: 'Kichererbsen-Avocado-Salat',
    meal: ['dinner', 'lunch'],
    minutes: 10,
    servings: 1,
    ingredients: [
      '1 Dose Kichererbsen (240 g abgetropft)',
      '½ Avocado (70 g)',
      '100 g Gurke',
      '100 g Kirschtomaten',
      '1 Stück rote Zwiebel',
      '2 TL Olivenöl',
      '1 EL Zitronensaft',
      'Petersilie, Salz, Pfeffer',
    ],
    steps: [
      'Kichererbsen abspülen und abtropfen lassen.',
      'Gurke, Tomaten, Avocado und Zwiebel klein schneiden.',
      'Alles mit Öl, Zitronensaft und gehackter Petersilie mischen.',
      'Mit Salz und Pfeffer abschmecken.',
    ],
    kcal: 538, protein: 20, carbs: 42, fat: 27,
    fiber: 24, sugar: 8, sat_fat: 4, salt: 1.5,
    restrictions: ['vegan', 'vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['mediterranean'],
  },
  {
    id: 'c-dattel-kakao-energy-balls',
    title: 'Dattel-Kakao-Energy-Balls',
    meal: ['snack'],
    minutes: 15,
    servings: 4,
    ingredients: [
      '100 g Datteln (entsteint)',
      '60 g Haferflocken',
      '40 g Erdnussmus',
      '15 g Backkakao',
    ],
    steps: [
      'Datteln 5 Minuten in heißem Wasser einweichen und abtropfen lassen.',
      'Alle Zutaten im Mixer zu einer klebrigen Masse verarbeiten.',
      'Mit feuchten Händen 12 Kugeln formen.',
      'Im Kühlschrank fest werden lassen (hält 1 Woche).',
    ],
    kcal: 203, protein: 6, carbs: 27, fat: 7,
    fiber: 5, sugar: 16, sat_fat: 2, salt: 0.0,
    restrictions: ['vegan', 'vegetarian', 'pescetarian', 'unprocessed'],
    macros: [],
  },
  {
    id: 'c-hummus-gemuesesticks',
    title: 'Hausgemachter Hummus mit Gemüsesticks',
    meal: ['snack', 'lunch'],
    minutes: 15,
    servings: 2,
    ingredients: [
      '1 Dose Kichererbsen (240 g abgetropft)',
      '30 g Tahini',
      '1 EL Olivenöl',
      'Saft von ½ Zitrone',
      '1 Knoblauchzehe',
      '2 Karotten (200 g)',
      '½ Gurke (200 g)',
      '1 Paprika (150 g)',
      'Kreuzkümmel, Salz',
    ],
    steps: [
      'Kichererbsen mit Tahini, Öl, Zitronensaft, Knoblauch, Gewürzen und 3–4 EL Wasser cremig pürieren.',
      'Mit Salz abschmecken.',
      'Gemüse in Sticks schneiden.',
      'Hummus mit den Sticks servieren.',
    ],
    kcal: 378, protein: 13, carbs: 30, fat: 19,
    fiber: 15, sugar: 11, sat_fat: 3, salt: 1.2,
    restrictions: ['vegan', 'vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['mediterranean'],
  },
  {
    id: 'c-edamame-chili-salz',
    title: 'Edamame mit Chili-Salz',
    meal: ['snack'],
    minutes: 8,
    servings: 1,
    ingredients: [
      '150 g Edamame (TK, geschält)',
      'Meersalz, Chiliflocken',
    ],
    steps: [
      'Edamame in kochendem Wasser 4–5 Minuten garen.',
      'Abgießen und gut abtropfen lassen.',
      'Mit Meersalz und Chiliflocken bestreuen.',
    ],
    kcal: 178, protein: 16, carbs: 8, fat: 8,
    fiber: 8, sugar: 3, sat_fat: 1, salt: 1.0,
    restrictions: ['vegan', 'vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['high_protein', 'low_carb', 'keto'],
  },
  {
    id: 'c-magerquark-heidelbeeren',
    title: 'Vanille-Quark mit Heidelbeeren',
    meal: ['snack', 'breakfast'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '250 g Magerquark',
      '100 g Heidelbeeren',
      '30 ml Milch',
      '1 TL Honig',
      'Mark von ¼ Vanilleschote oder etwas Vanillepulver',
    ],
    steps: [
      'Quark mit Milch, Honig und Vanille cremig rühren.',
      'Heidelbeeren unterheben oder darauf verteilen.',
    ],
    kcal: 239, protein: 32, carbs: 23, fat: 1,
    fiber: 5, sugar: 23, sat_fat: 1, salt: 0.3,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['balanced', 'high_protein', 'low_carb'],
  },
  {
    id: 'c-huettenkaese-tomaten-kuerbiskerne',
    title: 'Hüttenkäse mit Tomaten und Kürbiskernen',
    meal: ['snack'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '200 g Hüttenkäse',
      '100 g Kirschtomaten',
      '15 g Kürbiskerne',
      'Schnittlauch, Pfeffer',
    ],
    steps: [
      'Tomaten halbieren.',
      'Hüttenkäse in eine Schale geben und Tomaten darauf verteilen.',
      'Kürbiskerne in einer trockenen Pfanne kurz rösten und darüberstreuen.',
      'Mit Schnittlauch und Pfeffer würzen.',
    ],
    kcal: 306, protein: 30, carbs: 9, fat: 16,
    fiber: 2, sugar: 8, sat_fat: 7, salt: 1.5,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['high_protein', 'low_carb', 'keto'],
  },
  {
    id: 'c-apfel-mandelmus',
    title: 'Apfelspalten mit Mandelmus',
    meal: ['snack'],
    minutes: 3,
    servings: 1,
    ingredients: [
      '1 Apfel (180 g)',
      '20 g Mandelmus',
      '1 Prise Zimt',
    ],
    steps: [
      'Apfel entkernen und in Spalten schneiden.',
      'Mandelmus in ein Schälchen geben und mit Zimt bestreuen.',
      'Apfelspalten eintunken.',
    ],
    kcal: 225, protein: 5, carbs: 23, fat: 11,
    fiber: 6, sugar: 19, sat_fat: 1, salt: 0.0,
    restrictions: ['vegan', 'vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['low_carb'],
  },
  {
    id: 'c-griechischer-joghurt-walnuss-honig',
    title: 'Griechischer Joghurt mit Walnüssen und Honig',
    meal: ['snack', 'breakfast'],
    minutes: 3,
    servings: 1,
    ingredients: [
      '200 g griechischer Joghurt (2 %)',
      '20 g Walnüsse',
      '10 g Honig',
    ],
    steps: [
      'Joghurt in eine Schale geben.',
      'Walnüsse grob hacken und darüberstreuen.',
      'Mit Honig beträufeln.',
    ],
    kcal: 309, protein: 21, carbs: 17, fat: 17,
    fiber: 1, sugar: 17, sat_fat: 4, salt: 0.2,
    restrictions: ['vegetarian', 'pescetarian', 'unprocessed'],
    macros: ['high_protein', 'low_carb', 'mediterranean'],
  },
  {
    id: 'c-schoko-erdnuss-proteinshake',
    title: 'Schoko-Erdnuss-Proteinshake',
    meal: ['snack', 'breakfast'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '300 ml Milch (1,5 %)',
      '30 g Whey-Proteinpulver (Schoko)',
      '1 kleine Banane (100 g)',
      '15 g Erdnussmus',
      '1 TL Backkakao',
    ],
    steps: [
      'Alle Zutaten in den Mixer geben.',
      '30 Sekunden auf höchster Stufe mixen.',
      'Nach Wunsch mit Eiswürfeln servieren.',
    ],
    kcal: 457, protein: 39, carbs: 39, fat: 15,
    fiber: 5, sugar: 33, sat_fat: 6, salt: 0.5,
    restrictions: ['vegetarian', 'pescetarian'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-veganer-beeren-protein-smoothie',
    title: 'Veganer Beeren-Protein-Smoothie',
    meal: ['snack', 'breakfast'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '300 ml Sojadrink natur',
      '30 g veganes Proteinpulver',
      '150 g Beerenmischung (TK)',
      '½ Banane (60 g)',
      '20 g Haferflocken',
    ],
    steps: [
      'Alle Zutaten in den Mixer geben.',
      'Cremig mixen, bei Bedarf etwas Wasser zugeben.',
      'Sofort trinken.',
    ],
    kcal: 413, protein: 39, carbs: 37, fat: 10,
    fiber: 12, sugar: 20, sat_fat: 2, salt: 0.8,
    restrictions: ['vegan', 'vegetarian', 'pescetarian'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-hafer-bananen-masse-shake',
    title: 'Hafer-Bananen-Masse-Shake',
    meal: ['snack', 'breakfast'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '400 ml Milch (1,5 %)',
      '80 g Haferflocken (zart)',
      '40 g Whey-Proteinpulver (Vanille)',
      '1 Banane (120 g)',
      '30 g Erdnussmus',
    ],
    steps: [
      'Haferflocken im Mixer kurz fein mahlen.',
      'Übrige Zutaten zugeben.',
      '45 Sekunden cremig mixen und direkt trinken.',
    ],
    kcal: 930, protein: 64, carbs: 96, fat: 29,
    fiber: 12, sugar: 43, sat_fat: 9, salt: 0.6,
    restrictions: ['vegetarian', 'pescetarian'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-schoko-quark-mousse',
    title: 'Schoko-Quark-Mousse',
    meal: ['snack'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '250 g Magerquark',
      '10 g Backkakao',
      '50 ml Milch',
      '15 g Honig',
      '10 g Zartbitterschokolade (70 %)',
    ],
    steps: [
      'Quark mit Kakao, Milch und Honig luftig aufschlagen.',
      'In ein Glas füllen.',
      'Schokolade fein hacken und darüberstreuen.',
    ],
    kcal: 330, protein: 35, carbs: 29, fat: 8,
    fiber: 4, sugar: 27, sat_fat: 4, salt: 0.3,
    restrictions: ['vegetarian', 'pescetarian'],
    macros: ['balanced', 'high_protein'],
  },
  {
    id: 'c-bananen-nicecream-erdnuss',
    title: 'Bananen-Nicecream mit Erdnussmus',
    meal: ['snack'],
    minutes: 5,
    servings: 1,
    ingredients: [
      '2 gefrorene Bananen (200 g)',
      '2 EL Sojadrink',
      '15 g Erdnussmus',
      '1 TL Backkakao',
    ],
    steps: [
      'Gefrorene Bananenstücke mit Sojadrink im Mixer cremig pürieren.',
      'Kakao kurz untermixen.',
      'In eine Schale füllen und mit Erdnussmus toppen.',
    ],
    kcal: 301, protein: 8, carbs: 42, fat: 9,
    fiber: 7, sugar: 35, sat_fat: 2, salt: 0.0,
    restrictions: ['vegan', 'vegetarian', 'pescetarian'],
    macros: [],
  },
]
